POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNoYWFraWxhYWtpIiwiaWQiOiI2NjIxMDFlOTE4MDg5NDM4YmYyY2ViZDkiLCJpYXQiOjE3MTM3Nzg1NDB9.JMsf7vt5Wiyuzzm4j8KHxz2a_FVSLxX2crqEdhC--J8

{
    "content": "Single page apps use token based auth",
    "important": true,    
}